package de.minebench.syncinv.messenger;

import org.bukkit.util.io.BukkitObjectOutputStream;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectOutput;
import java.io.Serializable;
import java.util.ArrayDeque;
import java.util.Collections;
import java.util.Queue;

/*
 * Copyright 2017 Phoenix616 All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation,  version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
public class Message implements Serializable {

    private final String sender;
    private final MessageType type;
    private final Queue<Object> data = new ArrayDeque<>();

    /**
     * A Message of a certain type. Optionally with some data
     * @param type      The type of the message
     * @param objects   The data, in the order that it should be send
     * @throws IllegalArgumentException when the amount of Objects given didn't match the MessageType requirements
     */
    public Message(String sender, MessageType type, Object... objects) {
        if (objects.length < type.getArgCount()) {
            throw new IllegalArgumentException(type + " requires at least " + type.getArgCount() + " arguments. Only " + objects.length + " were given!");
        }
        this.sender = sender;
        this.type = type;
        if (objects.length > 0) {
            Collections.addAll(data, objects);
        }
    }

    public String getSender() {
        return sender;
    }

    public MessageType getType() {
        return type;
    }

    public Message add(Object o) {
        data.add(o);
        return this;
    }

    /**
     * Get the data
     * @return The data Queue
     */
    public Queue getData() {
        return data;
    }

    /**
     * Read the first object in this message
     * @return The first object
     */
    public Object read() {
        return data.poll();
    }

    /**
     * Generate a byte array out of the data of this message
     * @return          The generated byte array (starts with the sender,
     *                  then continues with the type and the data);
     *                  an empty one if an error occurred
     */
    public byte[] toByteArray() {
        try (ByteArrayOutputStream bos = new ByteArrayOutputStream();
             ObjectOutput out = new BukkitObjectOutputStream(bos)) {
            out.writeObject(this);
            return bos.toByteArray();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return new byte[0];
    }
}
